[tools]
pnpm = "latest"
node = ["latest", "20"]
python = "3.12"
java = ["latest", "21", "17"]
gradle = "8.6"
fd = "latest"
fzf = "latest"
ripgrep = "latest"
stylua = "latest"
bat = "latest"
git = "latest"
neovim = "nightly"
lua = "latest"
lua-language-server = "latest"
ffmpeg = "latest"

