[editor]
shell = ["fish", "-c"]
color-modes = true
line-number = "relative"
mouse = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "version-control", "file-modification-indicator"]
right = ["diagnostics", "register", "file-type", "position"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
