theme = "nord"

[editor]
shell = ["fish", "-c"]
color-modes = true
line-number = "relative"
mouse = false
idle-timeout = 0
preview-completion-insert = false
completion-replace = true
true-color = true
insert-final-newline = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "version-control", "separator",  "register", "file-type", "position"]
separator = " │"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true
skip-levels = 0
